(() => {
 'use strict';
 const $=id=>document.getElementById(id),K=TSKeyboard,C=TSCore,L=TSLessons;
 let data=C.defaults(),mode=null,session=null,shift=false,caps=false,hole=0,phraseId=null,finished=false,storageOK=true;
 const storageKey='typestory.v1';
 function storageWarning(){storageOK=false;$('storage-warning').hidden=false;$('storage-warning').textContent='此浏览器暂时无法自动保存进度。仍然可以练习，请在设置中导出备份。';}
 try{localStorage.setItem(storageKey+'.probe','1');localStorage.removeItem(storageKey+'.probe');const saved=localStorage.getItem(storageKey);if(saved)data=C.validate(JSON.parse(saved));}catch(_){storageWarning();}
 function save(){try{localStorage.setItem(storageKey,JSON.stringify(data));if(!storageOK){storageOK=true;$('storage-warning').hidden=true;}}catch(_){storageWarning();}}
 function sound(kind){TSAudio.play(kind,data.settings);}
 function textChar(c){return c===' '?'␣':c;}
 function selectedStage(){return Number($('stage').value)||0;}
 function applySettings(){document.body.dataset.size=data.settings.size;for(const id of ['layout','size','volume','mute']){if(id==='mute')$(id).checked=data.settings[id];else $(id).value=data.settings[id];}renderKeyboard();}
 function renderKeyboard(){
  $('keyboard').replaceChildren();K.rows.forEach(row=>{const div=document.createElement('div');div.className='key-row';row.forEach(k=>{const el=document.createElement('div');el.className='key'+(k.base.length>1?' function':'')+(['KeyF','KeyJ'].includes(k.code)?' home':'');el.dataset.code=k.code;el.style.setProperty('--width',k.width);if(k.finger)el.style.setProperty('--finger',K.colors[k.finger]);const label=document.createElement('span');let value=k.base;if(k.base.length===1)value=(shift||(caps&&/^Key/.test(k.code)))?k.upper:k.base;if(k.code==='Space')value='空格';if(data.settings.layout==='windows'){value=({AltLeft:'alt',AltRight:'alt',MetaLeft:'win',MetaRight:'win',Enter:'enter',Backspace:'backspace',Fn:'menu'})[k.code]||value;}label.textContent=value;el.append(label);div.append(el);});$('keyboard').append(div);});
  $('hands').replaceChildren();for(const hand of ['left','right']){const div=document.createElement('div');div.className='hand';const title=document.createElement('span');title.className='hand-label';title.textContent=hand==='left'?'左手':'右手';div.append(title);for(const finger of hand==='left'?['pinky','ring','middle','index','thumb']:['thumb','index','middle','ring','pinky']){const el=document.createElement('span');el.className='finger '+finger;el.dataset.hand=hand;el.dataset.finger=finger;el.style.setProperty('--finger',K.colors[finger]);el.textContent=K.names[finger];div.append(el);}$('hands').append(div);}renderTarget();
 }
 function keyEl(code){return $('keyboard').querySelector('[data-code="'+code+'"]');}
 function teaching(char){const g=K.guidance(char);if(!g)return '';const basic=g.key.code==='Space'?'空格':g.key.base;return g.label+'按 '+basic+(g.shift?'，'+(g.key.hand==='left'?'右手':'左手')+'小指按住 Shift':'')+' · 眼睛看屏幕';}
 function renderTarget(){
  document.querySelectorAll('.target,.shift-target').forEach(el=>el.classList.remove('target','shift-target'));
  document.querySelectorAll('.mini-mole,.key .mole-letter').forEach(el=>el.remove());document.querySelectorAll('.finger.active').forEach(el=>el.classList.remove('active'));
  const playing=session&&session.active;const show=mode==='free'||!playing||$('help').checked||session.hinted;
  $('keyboard-area').hidden=!show;$('guidance').textContent='';
  if(!playing||mode==='free')return;
  const char=session.expected,g=K.guidance(char);if(g&&show){const el=keyEl(g.key.code);el.classList.add('target');if(g.shift)keyEl(g.shiftCode).classList.add('shift-target');$('guidance').textContent=teaching(char);document.querySelectorAll('.finger').forEach(f=>{if((f.dataset.hand===g.key.hand||g.key.hand==='both')&&f.dataset.finger===g.key.finger||g.shift&&f.dataset.hand!==g.key.hand&&f.dataset.finger==='pinky')f.classList.add('active');});if(mode==='mole'&&$('help').checked){const mole=document.createElement('div');mole.className='mini-mole';const letter=document.createElement('span');letter.className='mole-letter';letter.textContent=char;el.append(mole,letter);}}
  if(mode==='mole')renderHoles();
  if(mode==='phrase'){const board=$('phrase-board');board.replaceChildren();[...session.target].forEach((c,i)=>{const el=document.createElement('span');el.className='char '+(i<session.index?'done':i===session.index?'current':'pending');el.textContent=textChar(c);el.setAttribute('aria-label',(i<session.index?'已完成 ':i===session.index?'当前输入 ':'未开始 ')+(c===' '?'空格':c));board.append(el);});}
 }
 function renderHoles(){const visible=mode==='mole'&&!$('help').checked&&session&&session.active;$('holes').hidden=!visible;$('holes').replaceChildren();if(!visible)return;for(let i=0;i<9;i++){const div=document.createElement('div');div.className='hole';if(i===hole){const img=document.createElement('img');img.src='assets/images/mole.svg';img.alt='等待输入的地鼠';const char=document.createElement('span');char.className='mole-letter';char.textContent=session.expected;div.append(img,char);}$('holes').append(div);}}
 function updateStats(){if(!session){$('score').textContent='准备开始';$('time').textContent='';$('accuracy').textContent='';$('progress').textContent='';return;}$('score').textContent=mode==='mole'?'⭐ '+session.correct+' 分':'✓ '+session.correct+' 次正确';$('time').textContent=mode==='mole'?'⏱ 剩余 '+Math.ceil((60000-session.elapsed)/1000)+' 秒':'⏱ '+Math.floor(session.elapsed/1000)+' 秒';$('accuracy').textContent='准确率 '+session.accuracy+'%';$('progress').textContent=mode==='phrase'?'进度 '+session.index+'/'+session.target.length+' · 求助 '+session.hints+' 次':'求助 '+session.hints+' 次';}
 function selectMode(next){stop();mode=next;$('home').hidden=true;$('play').hidden=false;$('mode-title').textContent={free:'键盘探索',mole:'地鼠出没',phrase:'短句小径'}[mode];$('free-display').hidden=mode!=='free';$('phrase-board').hidden=mode!=='phrase';$('phrase-board').replaceChildren();$('stage-label').hidden=mode==='free';$('help-label').hidden=mode==='free';$('stage').replaceChildren();(mode==='phrase'?L.phrases:L.stages).forEach((s,i)=>{const o=document.createElement('option');o.value=i;o.textContent=s.name;$('stage').append(o);});if(mode==='phrase'){$('stage').value=data.progress.stage;$('help').checked=data.progress.help;}$('message').textContent=mode==='free'?'点击开始，然后用实体键盘探索。':'选择阶段与帮助模式，准备好了就开始。';$('start').textContent=mode==='phrase'?'继续练习':'开始练习';renderKeyboard();updateStats();}
 function stop(){session=null;finished=false;$('result').hidden=true;$('pause').hidden=true;$('hint').hidden=true;$('holes').hidden=true;$('start').hidden=false;$('stage').disabled=false;$('help').disabled=false;}
 function newMole(){const chars=L.stages[selectedStage()].chars;const pool=[...chars].filter(c=>c!==session.target);session.target=pool[Math.floor(Math.random()*pool.length)]||chars[0];session.hinted=false;hole=Math.floor(Math.random()*9);}
 function start(){TSAudio.enable();finished=false;$('result').hidden=true;const now=performance.now();if(mode==='phrase'){data.progress.stage=selectedStage();data.progress.help=$('help').checked;phraseId=C.pickPhrase(data.progress,selectedStage());data.progress.current=phraseId;const [s,i]=phraseId.split(':').map(Number);session=new C.Session(mode,L.phrases[s].texts[i],now);save();}else{session=new C.Session(mode,'',now);if(mode==='mole')newMole();}$('stage').disabled=true;$('help').disabled=true;$('start').hidden=true;$('pause').hidden=false;$('pause').textContent='暂停';$('hint').hidden=mode==='free'||$('help').checked;$('message').textContent=mode==='free'?'双手轻放在 F 和 J，随意敲一敲。':'准确比快更重要，地鼠会等你。';renderTarget();updateStats();}
 function pause(){if(!session||!session.active||session.paused)return;session.pause(performance.now());if(!session.active){finish();return;}$('pause').textContent='继续练习';$('message').textContent='已暂停，准备好后点击继续练习。';}
 function finish(){if(finished)return;finished=true;sound('complete');if(mode==='phrase'){data.progress.completed[phraseId]=true;data.progress.last[selectedStage()]=phraseId;data.progress.current=null;const old=data.progress.best[phraseId];data.progress.best[phraseId]={accuracy:Math.max(old?old.accuracy:0,session.accuracy),seconds:Math.min(old?old.seconds:Infinity,session.elapsed/1000)};save();}$('pause').hidden=true;$('hint').hidden=true;$('stage').disabled=false;$('help').disabled=false;$('start').hidden=false;$('start').textContent=mode==='phrase'?'下一条练习':'再挑战一次';$('result').hidden=false;$('result').replaceChildren();const h=document.createElement('h2');h.textContent=mode==='phrase'?'🌼 小句子完成啦！':'🌼 这一局，做得不错！';const p=document.createElement('p');p.textContent=(mode==='mole'?'得分 '+session.correct+' · ':'耗时 '+(session.elapsed/1000).toFixed(1)+' 秒 · ')+'准确率 '+session.accuracy+'% · 求助 '+session.hints+' 次';const mistakes=document.createElement('p');const top=Object.entries(session.mistakes).sort((a,b)=>b[1]-a[1]).slice(0,3);mistakes.textContent=top.length?'下次一起练：'+top.map(([c,n])=>textChar(c)+'（'+n+' 次）').join('、'):'每一次都输入正确，继续保持！';const again=document.createElement('button');again.className='primary';again.textContent=mode==='phrase'?'继续下一条':'再练一次';again.onclick=start;const back=document.createElement('button');back.textContent='回花园选模式';back.onclick=goHome;$('result').append(h,p,mistakes,again,back);$('message').textContent='休息一下手指，也看看远处。';updateStats();renderTarget();}
 function goHome(){stop();mode=null;$('home').hidden=false;$('play').hidden=true;}
 function flash(el,cls){if(!el)return;el.classList.remove(cls);void el.offsetWidth;el.classList.add(cls);setTimeout(()=>el.classList.remove(cls),250);}
 document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>selectMode(b.dataset.mode));$('back').onclick=goHome;document.querySelector('.brand').onclick=e=>{e.preventDefault();goHome();};$('start').onclick=start;$('pause').onclick=()=>{if(session.paused){TSAudio.enable();session.resume(performance.now());$('pause').textContent='暂停';$('message').textContent='继续出发，小手指！';}else pause();};$('hint').onclick=()=>{if(session&&session.hint()){renderTarget();updateStats();}};
 $('stage').onchange=()=>{if(mode==='phrase'){data.progress.stage=selectedStage();save();}updateStats();};$('help').onchange=()=>{if(mode==='phrase'){data.progress.help=$('help').checked;save();}renderTarget();};
 window.addEventListener('keydown',e=>{
  if(e.isComposing||e.key==='Process'){if(session&&session.active)$('message').textContent='请先切换到 ABC / 英文输入源。';return;}
  const nextCaps=e.getModifierState('CapsLock'),nextShift=e.shiftKey;if(nextCaps!==caps||nextShift!==shift){caps=nextCaps;shift=nextShift;$('caps').hidden=!caps;renderKeyboard();}
  if(!mode||$('settings').open||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;
  if(e.metaKey||e.ctrlKey||e.altKey)return;
  if(session&&session.active&&!session.paused&&e.key.length===1)e.preventDefault();
  if(session&&session.active&&['Tab','Backspace','Enter',' ','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))e.preventDefault();
  const el=keyEl(e.code);if(el)el.classList.add('pressed');if(e.repeat||!session||!session.active||session.paused)return;
  if(mode==='free'){if(e.key.length===1){const g=K.guidance(e.key);document.querySelectorAll('.finger').forEach(f=>f.classList.toggle('active',!!g&&((f.dataset.hand===g.key.hand||g.key.hand==='both')&&f.dataset.finger===g.key.finger||g.shift&&f.dataset.hand!==g.key.hand&&f.dataset.finger==='pinky')));$('typed').textContent=textChar(e.key);$('free-finger').textContent=teaching(e.key)||'这个字符暂时没有对应的美式键位';sound('key');}return;}
  if(e.key.length!==1)return;
  const expected=session.expected,outcome=session.input(e.key,performance.now());if(outcome==='ignored'){if(!session.active)finish();return;}
  if(outcome==='wrong'){sound('wrong');flash(mode==='phrase'?$('phrase-board').querySelector('.current'):$('help').checked?keyEl(K.find(expected).code):$('holes'),'wrong-feedback');$('message').textContent=caps&&/[a-z]/.test(expected)&&e.key===expected.toUpperCase()?'当前开启了大写锁定，按 Caps Lock 关闭再试试。':'再试一次，目标是 '+textChar(expected)+'。地鼠会等你。';}else{sound('correct');$('message').textContent='找到了！继续加油。';if(outcome==='complete'){finish();return;}session.hinted=false;if(mode==='mole')newMole();renderTarget();const target=mode==='phrase'?$('phrase-board').querySelector('.done:last-of-type'):mode==='mole'&&!$('help').checked?$('holes'):keyEl(K.find(session.expected).code);flash(target,'hit');}updateStats();
 });
 window.addEventListener('keyup',e=>{const el=keyEl(e.code);if(el)el.classList.remove('pressed');if(shift!==e.shiftKey){shift=e.shiftKey;renderKeyboard();}});
 window.addEventListener('blur',()=>{pause();shift=false;document.querySelectorAll('.pressed').forEach(el=>el.classList.remove('pressed'));renderKeyboard();});document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});
 setInterval(()=>{if(session&&session.active&&!session.paused){session.tick(performance.now());updateStats();if(!session.active)finish();}},100);
 $('settings-button').onclick=()=>{pause();$('saved-progress').textContent='已完成 '+Object.keys(data.progress.completed).length+' 条短句';$('settings').showModal();};
 for(const id of ['layout','size','volume','mute'])$(id).onchange=()=>{data.settings[id]=id==='mute'?$(id).checked:id==='volume'?Number($(id).value):$(id).value;applySettings();save();};
 $('export').onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='typestory-progress.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};$('import').onclick=()=>$('import-file').click();$('import-file').onchange=async()=>{const file=$('import-file').files[0];if(!file)return;try{if(file.size>1000000)throw Error('文件过大');const incoming=C.validate(JSON.parse(await file.text()));data=incoming;save();applySettings();if(mode==='phrase')selectMode('phrase');$('saved-progress').textContent='已完成 '+Object.keys(data.progress.completed).length+' 条短句';$('import-status').textContent='进度已导入。';}catch(error){$('import-status').textContent='未导入：'+error.message;}$('import-file').value='';};
 applySettings();
})();
